In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from pathlib import Path


DATA_PATH = Path(
    "../data/raw/adhd200_preprocessed_phenotypics.tsv"
)


df = pd.read_csv(
    DATA_PATH,
    sep="\t"
)


df.head()

,ScanDir ID,Site,Gender,Age,Handedness,DX,Secondary Dx,ADHD Measure,ADHD Index,Inattentive,Hyper/Impulsive,IQ Measure,Verbal IQ,Performance IQ,Full2 IQ,Full4 IQ,Med Status,QC_Athena,QC_NIAK
0,2371032,3,0.0,10.73,1,0,NaN,2,47,55,43,1.0,121.0,119.0,NaN,122.0,1,1.0,1.0
1,2026113,3,0.0,12.99,1,1,NaN,2,90,89,78,1.0,122.0,108.0,NaN,106.0,1,1.0,1.0
2,3434578,3,0.0,8.12,1,0,NaN,2,42,42,43,1.0,85.0,98.0,NaN,89.0,1,1.0,1.0
3,8628223,3,0.0,10.81,1,0,Simple phobia,2,42,49,49,1.0,85.0,86.0,NaN,97.0,1,1.0,1.0
4,1623716,3,0.0,12.65,1,1,NaN,2,87,90,90,1.0,89.0,88.0,NaN,89.0,1,1.0,1.0

In [2]:
df.shape

(973, 19)

In [3]:
df["DX"].value_counts()

DX
0          585
1          212
3          137
pending     26
2           13
Name: count, dtype: int64

In [4]:
df.describe()

,ScanDir ID,Site,Gender,Age,IQ Measure,Verbal IQ,Performance IQ,Full2 IQ,Full4 IQ,QC_Athena,QC_NIAK
count,9.730000e+02,973.000000,972.000000,973.000000,899.000000,725.000000,725.000000,164.000000,898.000000,965.000000,965.000000
mean,1.940929e+06,4.150051,0.616255,12.034872,1.273637,31.234483,25.713103,-520.225610,97.578842,0.929534,0.948187
std,2.311618e+06,2.257610,0.486547,3.328270,33.409364,289.861555,288.312825,549.704955,122.956864,0.256064,0.221765
min,1.000100e+04,1.000000,0.000000,7.090000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0.000000,0.000000
25%,1.605400e+04,1.000000,0.000000,9.330000,2.000000,100.000000,93.000000,-999.000000,102.000000,1.000000,1.000000
50%,1.471736e+06,5.000000,1.000000,11.420000,2.000000,111.000000,106.000000,-999.000000,111.000000,1.000000,1.000000
75%,3.190461e+06,6.000000,1.000000,14.000000,3.000000,121.000000,116.000000,106.250000,120.750000,1.000000,1.000000
max,9.956994e+06,8.000000,1.000000,26.310000,5.000000,158.000000,143.000000,139.000000,153.000000,1.000000,1.000000

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 973 entries, 0 to 972
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ScanDir ID       973 non-null    int64
 1   Site             973 non-null    int64
 2   Gender           972 non-null    float64
 3   Age              973 non-null    float64
 4   Handedness       970 non-null    str
 5   DX               973 non-null    str
 6   Secondary Dx     157 non-null    str
 7   ADHD Measure     655 non-null    str
 8   ADHD Index       613 non-null    str
 9   Inattentive      692 non-null    str
 10  Hyper/Impulsive  692 non-null    str
 11  IQ Measure       899 non-null    float64
 12  Verbal IQ        725 non-null    float64
 13  Performance IQ   725 non-null    float64
 14  Full2 IQ         164 non-null    float64
 15  Full4 IQ         898 non-null    float64
 16  Med Status       664 non-null    str
 17  QC_Athena        965 non-null    float64
 18  QC_NIAK          965 non-null    float64
dtypes: float64(9), int64(2), str(8)
memory usage: 144.6 KB